### ISSUE TITLE
[jsc] ASSERTION FAILED: from.isCell() && from.asCell()->JSCell::inherits(&WTF::RemovePointer<To>::Type::s_info)

### ISSUE THREAD

**Issue by guijemont** [Metrological/buildroot#48]
When running activation-test-loop.js from a later upstream webkit implementation, I get the assertion failure:
```
ASSERTION FAILED: from.isCell() && from.asCell()->JSCell::inherits(&WTF::RemovePointer<To>::Type::s_info)
runtime/JSCell.h(182) : To JSC::jsCast(JSC::JSValue) [with To = JSC::JSActivation*]
```
And this is the corresponding backtrace:
```
#0  0x005f4c8c in WTFCrash () at wtf/Assertions.cpp:345
#1  0x0031e310 in jsCast<JSC::JSActivation*> (from=...) at runtime/JSCell.h:182
#2  JSC::JITStubThunked_op_tear_off_activation (args=0xbefff360) at jit/JITStubs.cpp:2447
#3  0x00316840 in cti_op_tear_off_activation ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by guijemont** [comment]
Closing as WONTFIX as this seems to be a corner case we won't meet in production.
