### ISSUE TITLE
[jsc] segfault in tricky-infinite-loop-that-uses-captured-variables-and-creates-the-activation-outside-the-loop.js

### ISSUE THREAD

**Issue by guijemont** [Metrological/buildroot#49]
That stress test segfaults, with the following stack trace (stack trace obtained on x64):
```
Program received signal SIGSEGV, Segmentation fault.
JSC::Interpreter::unwindCallFrame (this=this@entry=0x7ffff7ecdd80, callFrame=@0x7fffffffd270: 0x7fffb10cd088, exceptionValue=..., 
    bytecodeOffset=@0x7fffffffd17c: 23, codeBlock=@0x7fffffffd1d0: 0x7ffff7f10dc0) at runtime/JSActivation.h:147
147         inline int JSActivation::registersOffset(SharedSymbolTable* symbolTable)
(gdb) bt
#0  JSC::Interpreter::unwindCallFrame (this=this@entry=0x7ffff7ecdd80, callFrame=@0x7fffffffd270: 0x7fffb10cd088, exceptionValue=..., 
    bytecodeOffset=@0x7fffffffd17c: 23, codeBlock=@0x7fffffffd1d0: 0x7ffff7f10dc0) at runtime/JSActivation.h:147
#1  0x00000000005ba5e5 in JSC::Interpreter::throwException (this=0x7ffff7ecdd80, callFrame=@0x7fffffffd270: 0x7fffb10cd088, exceptionValue=..., 
    bytecodeOffset=23) at interpreter/Interpreter.cpp:740
#2  0x00000000005df6a3 in genericThrow (vPCIndex=<optimized out>, exceptionValue=..., callFrame=0x7fffb10cd088, vm=0x7ffff7ecf000) at jit/JITExceptions.cpp:45
#3  JSC::jitThrow (vm=0x7ffff7ecf000, callFrame=0x7fffb10cd100, exceptionValue=..., faultLocation=...) at jit/JITExceptions.cpp:67
#4  0x0000000000604de9 in JSC::cti_op_throw (args=0x7fffffffd2c0) at jit/JITStubs.cpp:3257
#5  0x00007fffb34d240f in ?? ()
#6  0x0000000000000020 in ?? ()
#7  0x00007fffb104e070 in ?? ()
#8  0x00007ffff7ece710 in ?? ()
#9  0x00007ffff7edb4e0 in ?? ()
#10 0x0000000000000000 in ?? ()

```

**Comment by guijemont** [comment]
Closing as WONTFIX as this seems to be a corner case we won't meet in production.
