### ISSUE TITLE
[jsc] segfault in large-regexp.js

### ISSUE THREAD

**Issue by guijemont** [Metrological/buildroot#50]
That stress test segfaults, with the following stack trace (stack trace obtained on x64):
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000007ad10c in WTFCrash () at wtf/Assertions.cpp:345
345         *(int *)(uintptr_t)0xbbadbeef = 0;
(gdb) bt
#0  0x00000000007ad10c in WTFCrash () at wtf/Assertions.cpp:345
#1  0x000000000079940f in overflowed () at ../WTF/wtf/CheckedArithmetic.h:80
#2  Checked<long> (rhs=..., this=<optimized out>) at ../WTF/wtf/CheckedArithmetic.h:459
#3  JSC::Yarr::YarrGenerator<(JSC::Yarr::YarrJITCompileMode)0>::generatePatternCharacterFixed (this=this@entry=0x7fffffffa270, opIndex=<optimized out>)
    at yarr/YarrJIT.cpp:873
#4  0x00000000007a2637 in JSC::Yarr::YarrGenerator<(JSC::Yarr::YarrJITCompileMode)0>::generateTerm (this=this@entry=0x7fffffffa270, opIndex=opIndex@entry=13)
    at yarr/YarrJIT.cpp:1223
#5  0x00000000007a28a3 in JSC::Yarr::YarrGenerator<(JSC::Yarr::YarrJITCompileMode)0>::generate (this=this@entry=0x7fffffffa270) at yarr/YarrJIT.cpp:1357
#6  0x00000000007a493d in JSC::Yarr::YarrGenerator<(JSC::Yarr::YarrJITCompileMode)0>::compile (this=this@entry=0x7fffffffa270, vm=vm@entry=0x7ffff7ecf000, 
    jitObject=...) at yarr/YarrJIT.cpp:2641
#7  0x00000000007984a9 in JSC::Yarr::jitCompile (pattern=..., charSize=charSize@entry=JSC::Yarr::Char8, vm=vm@entry=0x7ffff7ecf000, jitObject=..., 
    mode=mode@entry=JSC::Yarr::MatchOnly) at yarr/YarrJIT.cpp:2695
#8  0x00000000007750b7 in JSC::RegExp::compileMatchOnly (this=this@entry=0x7fffb0fafef0, vm=0x7ffff7ecf000, charSize=JSC::Yarr::Char8)
    at runtime/RegExp.cpp:405
#9  0x00000000007757ae in compileIfNecessaryMatchOnly (charSize=<optimized out>, vm=..., this=0x7fffb0fafef0) at runtime/RegExp.cpp:440
#10 JSC::RegExp::match (this=this@entry=0x7fffb0fafef0, vm=..., s=..., startOffset=startOffset@entry=0) at runtime/RegExp.cpp:450
#11 0x0000000000789b9e in performMatch (startOffset=0, input=..., string=<optimized out>, regExp=<optimized out>, vm=..., this=0x7fffb0f6fe70)
    at runtime/RegExpConstructor.h:125
#12 JSC::stringProtoFuncMatch (exec=0x7fffb10cd088) at runtime/StringPrototype.cpp:845
#13 0x00007fffb34d20e5 in ?? ()
#14 0xffff000000000002 in ?? ()
#15 0x000000000062949a in llint_op_call ()
#16 0x00007ffff7e2f870 in ?? ()
#17 0x00007fffffffd550 in ?? ()
#18 0x00007fffffffd4f0 in ?? ()
#19 0x00000000006eef5a in JSC::ProgramExecutable::initializeGlobalProperties (this=0x7fffffffd3b0, vm=..., callFrame=<optimized out>, scope=<optimized out>)
    at runtime/Executable.cpp:419
#20 0x00000000005bcd08 in execute (vm=0x7fffb0f4fe70, callFrame=0x7ffff7ecdd90, stack=0x7fffb10cd038, this=0x7fffb0f4fe90) at jit/JITCode.h:135
#21 JSC::Interpreter::execute (this=<optimized out>, program=program@entry=0x7fffb0f4fe70, callFrame=callFrame@entry=0x7ffff7e2f8d8, thisObj=<optimized out>)
    at interpreter/Interpreter.cpp:951
#22 0x00000000006cdc36 in JSC::evaluate (exec=0x7ffff7e2f8d8, source=..., thisValue=..., returnedException=returnedException@entry=0x7fffffffde80)
    at runtime/Completion.cpp:83
#23 0x000000000040f4cc in runWithScripts (dump=false, scripts=..., globalObject=0x7ffff7e2f870) at jsc.cpp:625
#24 jscmain (argc=<optimized out>, argv=argv@entry=0x7fffffffe198) at jsc.cpp:841
#25 0x0000000000407038 in main (argc=2, argv=0x7fffffffe198) at jsc.cpp:583
```

**Comment by guijemont** [comment]
Closing as WONTFIX as this seems to be a corner case we don't meet in production.
