### ISSUE TITLE
[jsc] segfault in new-array-dead.js

### ISSUE THREAD

**Issue by guijemont** [Metrological/buildroot#51]
That stress test segfaults, with the following stack trace (stack trace obtained on x64):
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000007ad10c in WTFCrash () at wtf/Assertions.cpp:345
345         *(int *)(uintptr_t)0xbbadbeef = 0;
(gdb) bt
#0  0x00000000007ad10c in WTFCrash () at wtf/Assertions.cpp:345
#1  0x00000000005b4fe8 in overflowed () at ../WTF/wtf/CheckedArithmetic.h:80
#2  at (i=4294967295, this=0x7fffffffc7a8) at ../WTF/wtf/Vector.h:561
#3  operator[] (i=4294967295, this=0x7fffffffc7a8) at ../WTF/wtf/Vector.h:581
#4  use (child=<optimized out>, this=0x7fffffffc7a0) at dfg/DFGScoreBoard.h:112
#5  use (child=..., this=0x7fffffffc7a0) at dfg/DFGScoreBoard.h:129
#6  useIfHasResult (child=..., this=0x7fffffffc7a0) at dfg/DFGScoreBoard.h:138
#7  JSC::DFG::VirtualRegisterAllocationPhase::run (this=this@entry=0x7fffffffca10) at dfg/DFGVirtualRegisterAllocationPhase.cpp:94
#8  0x00000000005b3359 in runAndLog<JSC::DFG::VirtualRegisterAllocationPhase> (phase=...) at dfg/DFGPhase.h:75
#9  runPhase<JSC::DFG::VirtualRegisterAllocationPhase> (graph=...) at dfg/DFGPhase.h:85
#10 JSC::DFG::performVirtualRegisterAllocation (graph=...) at dfg/DFGVirtualRegisterAllocationPhase.cpp:146
#11 0x000000000051547f in JSC::DFG::compile (compileMode=JSC::DFG::CompileFunction, exec=<optimized out>, codeBlock=0x7ffff7f0f600, jitCode=..., 
    jitCodeWithArityCheck=0x7fffb0f4fdc0, osrEntryBytecodeIndex=0) at dfg/DFGDriver.cpp:148
#12 0x00000000006ed377 in jitCompileFunctionIfAppropriate (effort=JSC::JITCompilationCanFail, bytecodeIndex=0, jitType=JSC::JITCode::DFGJIT, 
    jitCodeWithArityCheck=..., jitCode=..., codeBlock=..., exec=0x7fffb10cd0a0) at jit/JITDriver.h:95
#13 prepareFunctionForExecution (kind=JSC::CodeForCall, bytecodeIndex=0, jitType=JSC::JITCode::DFGJIT, jitCodeWithArityCheck=..., jitCode=..., codeBlock=..., 
    exec=0x7fffb10cd0a0) at runtime/ExecutionHarness.h:68
#14 compileForCallInternal (bytecodeIndex=0, jitType=JSC::JITCode::DFGJIT, scope=<optimized out>, exec=0x7fffb10cd0a0, this=0x7fffb0f4fd70)
    at runtime/Executable.cpp:544
#15 JSC::FunctionExecutable::compileOptimizedForCall (this=0x7fffb0f4fd70, exec=0x7fffb10cd0a0, scope=<optimized out>, bytecodeIndex=0)
    at runtime/Executable.cpp:465
#16 0x00000000005ff0d0 in JSC::cti_optimize (args=0x7fffffffd310) at jit/JITStubs.cpp:2039
#17 0x00007ffff34cf0ac in ?? ()
#18 0x0000000000000010 in ?? ()
#19 0x3ff9000000000000 in ?? ()
#20 0x400d000000000009 in ?? ()
#21 0x00007ffff7f18f40 in ?? ()
#22 0x0000000000000000 in ?? ()
```

**Comment by guijemont** [comment]
Closing as WONTFIX as this seems to be a corner case we won't meet in production.
