### ISSUE TITLE
JSC GC segfault

### ISSUE THREAD

**Issue by guijemont** [Metrological/buildroot#66]
While playing videos and doing "next" repetitively in youtube TV, I got this segfault:

```
#0  0xb573b5b0 in JSC::SlotVisitor::harvestWeakReferences (this=this@entry=0xb3df8) at /home/guijemont/dev/metrological/buildroot/output.qt53/build/qt5webkit-undefined/Source/JavaScriptCore/heap/SlotVisitor.cpp:326
#1  0xb5720428 in harvestWeakReferences (this=<optimized out>) at /home/guijemont/dev/metrological/buildroot/output.qt53/build/qt5webkit-undefined/Source/JavaScriptCore/heap/Heap.cpp:395
#2  JSC::Heap::markRoots (this=0xb69db2bc <JSC::MarkedBlock::clearMarks()::__PRETTY_FUNCTION__>, this@entry=0xaf588) at /home/guijemont/dev/metrological/buildroot/output.qt53/build/qt5webkit-undefined/Source/JavaScriptCore/heap/Heap.cpp:570
#3  0xb57219f0 in JSC::Heap::collect (this=0xaf588, sweepToggle=sweepToggle@entry=JSC::Heap::DoNotSweep) at /home/guijemont/dev/metrological/buildroot/output.qt53/build/qt5webkit-undefined/Source/JavaScriptCore/heap/Heap.cpp:727
#4  0xb5a2e580 in JSC::DefaultGCActivityCallback::doWork (this=<optimized out>) at /home/guijemont/dev/metrological/buildroot/output.qt53/build/qt5webkit-undefined/Source/JavaScriptCore/runtime/GCActivityCallback.cpp:96
#5  0xb5729dc0 in JSC::HeapTimer::timerEvent (this=0xaba30) at /home/guijemont/dev/metrological/buildroot/output.qt53/build/qt5webkit-undefined/Source/JavaScriptCore/heap/HeapTimer.cpp:159
#6  0xb2502054 in QObject::event(QEvent*) () from /home/guijemont/dev/metrological/buildroot/output.qt53/staging/usr/lib/libQt5Core.so.5
#7  0xb2c8d424 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/guijemont/dev/metrological/buildroot/output.qt53/staging/usr/lib/libQt5Widgets.so.5
#8  0xb2c9295c in QApplication::notify(QObject*, QEvent*) () from /home/guijemont/dev/metrological/buildroot/output.qt53/staging/usr/lib/libQt5Widgets.so.5
#9  0x00026d30 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by guijemont** [comment]
Closing as this could not be reproduced with recent versions of qtwebkit (5.4) and youtube TV.

**Comment by guijemont** [comment]
Closing as this could not be reproduced any more with qtwebkit 5.4 and recent youtube TV.
It is likely fixed by https://github.com/Metrological/qtwebkit/commit/c11db34e43f50727c142424531e659a05abc7cc7 though.
